// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiERP.Auth.Infrastructure.Data;

#nullable disable

namespace TaxiERP.Auth.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902015146_AdicionaAuditoriaESoftDelete")]
    partial class AdicionaAuditoriaESoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxiERP.Auth.Domain.Entities.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organizacoes");
                });

            modelBuilder.Entity("TaxiERP.Auth.Domain.Entities.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Descricao = "Pode visualizar a lista de motoristas",
                            Nome = "Motorista:Visualizar"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Descricao = "Pode cadastrar novos motoristas",
                            Nome = "Motorista:Criar"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Descricao = "Pode editar dados de motoristas",
                            Nome = "Motorista:Editar"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Descricao = "Pode deletar motoristas",
                            Nome = "Motorista:Deletar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Descricao = "Pode visualizar a lista de associados",
                            Nome = "Associado:Visualizar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Descricao = "Pode cadastrar novos associados",
                            Nome = "Associado:Criar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Descricao = "Pode editar dados de associados",
                            Nome = "Associado:Editar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Descricao = "Pode deletar associados",
                            Nome = "Associado:Deletar"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Descricao = "Pode visualizar a lista de banidos",
                            Nome = "Banido:Visualizar"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Descricao = "Pode banir usuários/motoristas",
                            Nome = "Banido:Criar"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Descricao = "Pode editar status de banidos",
                            Nome = "Banido:Editar"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Descricao = "Pode remover da lista de banidos",
                            Nome = "Banido:Deletar"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Descricao = "Pode visualizar ocorrências",
                            Nome = "Ocorrencia:Visualizar"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Descricao = "Pode registrar novas ocorrências",
                            Nome = "Ocorrencia:Criar"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Descricao = "Pode editar ocorrências",
                            Nome = "Ocorrencia:Editar"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Descricao = "Pode deletar ocorrências",
                            Nome = "Ocorrencia:Deletar"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Descricao = "Pode visualizar unidades",
                            Nome = "Unidade:Visualizar"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Descricao = "Pode cadastrar novas unidades",
                            Nome = "Unidade:Criar"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Descricao = "Pode editar unidades",
                            Nome = "Unidade:Editar"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Descricao = "Pode deletar unidades",
                            Nome = "Unidade:Deletar"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Descricao = "Pode visualizar a lista de usuários",
                            Nome = "Usuario:Visualizar"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Descricao = "Pode criar novos usuários",
                            Nome = "Usuario:Criar"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Descricao = "Pode editar usuários",
                            Nome = "Usuario:Editar"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            Descricao = "Pode deletar usuários",
                            Nome = "Usuario:Deletar"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            Descricao = "Pode criar seu próprio perfil (registro inicial)",
                            Nome = "Perfil:Criar"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            Descricao = "Pode editar seu próprio perfil",
                            Nome = "Perfil:Editar"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            Descricao = "Pode visualizar o dashboard principal",
                            Nome = "Dashboard:Visualizar"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            Descricao = "Pode enviar a solicitação de alteração de senha",
                            Nome = "Acao:AlterarSenha"
                        });
                });

            modelBuilder.Entity("TaxiERP.Auth.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavegadorCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SenhaCriada")
                        .HasColumnType("bit");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("OrganizacaoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TaxiERP.Auth.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("UsuarioPermissoes");
                });

            modelBuilder.Entity("TaxiERP.Auth.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("TaxiERP.Auth.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxiERP.Auth.Domain.Entities.Organizacao", "Organizacao")
                        .WithMany("Usuarios")
                        .HasForeignKey("OrganizacaoId");

                    b.Navigation("CriadoPor");

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("TaxiERP.Auth.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.HasOne("TaxiERP.Auth.Domain.Entities.Permissao", "Permissao")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("PermissaoId");

                    b.HasOne("TaxiERP.Auth.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Permissao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaxiERP.Auth.Domain.Entities.Organizacao", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TaxiERP.Auth.Domain.Entities.Permissao", b =>
                {
                    b.Navigation("UsuarioPermissoes");
                });

            modelBuilder.Entity("TaxiERP.Auth.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioPermissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
